# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/4232/radiation_processing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/4232/radiation_processing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/4232/radiation_processing/CMakeFiles /home/david/4232/radiation_processing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/4232/radiation_processing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named decon_main

# Build rule for target.
decon_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decon_main
.PHONY : decon_main

# fast build rule for target.
decon_main/fast:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/build
.PHONY : decon_main/fast

decon_main.o: decon_main.cc.o

.PHONY : decon_main.o

# target to build an object file
decon_main.cc.o:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/decon_main.cc.o
.PHONY : decon_main.cc.o

decon_main.i: decon_main.cc.i

.PHONY : decon_main.i

# target to preprocess a source file
decon_main.cc.i:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/decon_main.cc.i
.PHONY : decon_main.cc.i

decon_main.s: decon_main.cc.s

.PHONY : decon_main.s

# target to generate assembly for a file
decon_main.cc.s:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/decon_main.cc.s
.PHONY : decon_main.cc.s

src/data_read.o: src/data_read.cc.o

.PHONY : src/data_read.o

# target to build an object file
src/data_read.cc.o:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/data_read.cc.o
.PHONY : src/data_read.cc.o

src/data_read.i: src/data_read.cc.i

.PHONY : src/data_read.i

# target to preprocess a source file
src/data_read.cc.i:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/data_read.cc.i
.PHONY : src/data_read.cc.i

src/data_read.s: src/data_read.cc.s

.PHONY : src/data_read.s

# target to generate assembly for a file
src/data_read.cc.s:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/data_read.cc.s
.PHONY : src/data_read.cc.s

src/decon_space.o: src/decon_space.cc.o

.PHONY : src/decon_space.o

# target to build an object file
src/decon_space.cc.o:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/decon_space.cc.o
.PHONY : src/decon_space.cc.o

src/decon_space.i: src/decon_space.cc.i

.PHONY : src/decon_space.i

# target to preprocess a source file
src/decon_space.cc.i:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/decon_space.cc.i
.PHONY : src/decon_space.cc.i

src/decon_space.s: src/decon_space.cc.s

.PHONY : src/decon_space.s

# target to generate assembly for a file
src/decon_space.cc.s:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/decon_space.cc.s
.PHONY : src/decon_space.cc.s

src/gold.o: src/gold.cc.o

.PHONY : src/gold.o

# target to build an object file
src/gold.cc.o:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/gold.cc.o
.PHONY : src/gold.cc.o

src/gold.i: src/gold.cc.i

.PHONY : src/gold.i

# target to preprocess a source file
src/gold.cc.i:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/gold.cc.i
.PHONY : src/gold.cc.i

src/gold.s: src/gold.cc.s

.PHONY : src/gold.s

# target to generate assembly for a file
src/gold.cc.s:
	$(MAKE) -f CMakeFiles/decon_main.dir/build.make CMakeFiles/decon_main.dir/src/gold.cc.s
.PHONY : src/gold.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... decon_main"
	@echo "... edit_cache"
	@echo "... decon_main.o"
	@echo "... decon_main.i"
	@echo "... decon_main.s"
	@echo "... src/data_read.o"
	@echo "... src/data_read.i"
	@echo "... src/data_read.s"
	@echo "... src/decon_space.o"
	@echo "... src/decon_space.i"
	@echo "... src/decon_space.s"
	@echo "... src/gold.o"
	@echo "... src/gold.i"
	@echo "... src/gold.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

